### ISSUE TITLE
`Server` - Server backend for EVM -> DFC

### ISSUE THREAD

**Issue by weiyuan95** [WavesHQ/bridge#176]
### Blurb
This issue lists out the necessary tasks that we need to work on to successfully bridge tokens from EVM to DFC. It will state out the flow on how funds are bridged from Ethereum to DeFiChain from a server perspective, and then list out the tasks that need to be done to achieve that goal.

Take note that this _does not_ worry about any potential front end error handling, and is solely worried about bridging the funds. If the front end needs the server to return some kind of information for error handling, that task will need to be evaluated and added.

#### Ethereum Side

1. The server is listening for the [`BRIDGE_TO_DEFI_CHAIN` event](https://github.com/WavesHQ/bridge/blob/main/packages/smartcontracts/src/contracts/BridgeV1.sol#L122-L134) from the `ethers` [`contract.on` event listener](https://docs.ethers.org/v5/api/contract/contract/#Contract--events)
2. The bridge smart contract emits the event when a user calls the [`bridgeToDeFiChain` method](https://github.com/WavesHQ/bridge/blob/main/packages/smartcontracts/src/contracts/BridgeV1.sol#L265) successfully
    -  Take note that this is agnostic of the UI. Users can directly call this method without going through the UI. They will bear the risks of doing that themselves though.
    - These contracts are already have a baseline implementation, and can be seen [here](https://github.com/WavesHQ/bridge/tree/main/packages/smartcontracts/src/contracts) 
3. ~The server picks up the emitted [event](https://docs.ethers.org/v5/concepts/events/) . It then passes it off to a `TransactionConfirmerQueue` which queries the chain if the transaction has reached the required number of confirmations, and if not, add it back to the queue to check the confirmations after a certain period of time.~
   - ~When the event is emitted, it means that it has already successfully executed on the EVM, and has passed checks such as the daily allowance check, or that the user has a sufficient balance. The user would also already have deposited the requisite amount of funds. The server will only need to check for the necessary amount of confirmations before executing any follow up logic.~
       - ~These transactions already have at least 1 confirmation (since they are being emitted from a mined block) and are valid, so it's just a matter of waiting till it hits the necessary number of confirmations~
       - We can make a choice between 33 confirmations (safe, unlikely to change) or 65 confirmations(extremely safe, extremely unlikely to change). Reference to these values [here](https://www.alchemy.com/overviews/ethereum-commitment-levels)
    - ~There is an implementation I can refer to for the `TransactionConfirmerQueue`. I'll work on it.~
    - This implementation has changed, there'll be an upcoming PR for it. But essentially we'll be looking at historic blocks for final events instead of listening to events as they come from the chain. More explanation [here](https://github.com/WavesHQ/bridge/issues/186#issuecomment-1383572549)
5. When the transaction has reached the required number of confirmations, the server will start the process of sending tokens via Hot Wallet.

#### DeFiChain Side
6. Creating the transaction is like how it is created on Light wallet. It will be craft a raw transaction and will pass the account. Account is the "whale wallet" that is an initialized wallet of Hot Wallet(Wallet creation will be handled on a different ticket https://github.com/WavesHQ/bridge/issues/182). 
7. Assuming that the wallet has been created, the server will craft a `sendtoken` transaction and broadcast to DeFiChain. With the use of Hot Wallet. The server will have access to the private key of the Hot Wallet.
8. Once the transaction has been completed (need to check the confirmation number), then it will be a success.

### Tasks
High level tasks that need to be done to execute the flow above. Anything more specific can be tracked in sub issues that are spawn from this one.
- [ ] Server needs to be able to listen to the emitted `BRIDGE_TO_DEFI_CHAIN` event from Ethereum #186
- [ ] A `TransactionConfirmerQueue` needs to be implemented to ensure that the transactions from the emitted events are safe (33 confirmations) or final (65 confirmations). I would say we go with 65 for finality, or 33 for speedier (but still relatively safe) transactions. #183 
- [ ] Server needs to be able to execute a token mint transaction via a RPC call to the consortium API #185

![image](https://user-images.githubusercontent.com/25013382/216222501-8e5b3bd5-dfbb-4a98-ad5b-d335c327ead4.png)

**Comment by thedoublejay** [comment]
Thanks for the write up @weiyuan95, added some info on this flow. Please have a look @pierregee @lykalabrada @fullstackninja864

**Comment by thedoublejay** [comment]
We can use 30 blocks for DeFiChain. ~15 mins

**Comment by lykalabrada** [comment]
Would it be weird to listen for `BRIDGE_TO_DEFI_CHAIN` event from the frontend instead of from the server? I was thinking maybe we can:
1. Listen for `BRIDGE_TO_DEFI_CHAIN` event from the frontend, then 
2. Once event is emitted we can show the success screen to the user, and then 
3. Call the server that will confirm the transaction and mint the DFC tokens after 30 blocks
@weiyuan95 @thedoublejay @pierregee

**Comment by weiyuan95** [comment]
> Would it be weird to listen for `BRIDGE_TO_DEFI_CHAIN` event from the frontend instead of from the server? I was thinking maybe we can:
> 
> 1. Listen for `BRIDGE_TO_DEFI_CHAIN` event from the frontend, then
> 2. Once event is emitted we can show the success screen to the user, and then
> 3. Call the server that will confirm the transaction and mint the DFC tokens after 30 blocks
>    @weiyuan95 @thedoublejay @pierregee

The thing about point 2: the event can be emitted, but the block that it is mined on is actually not part of the 'correct' chain. This is a natural process that comes with the consensus mechanisms of the chain.

Therefore, we should only process 'final' transactions, which happens around 60+ blocks from the tip of the current chain. I think it's possible to have a job that processes historic events (similar to the implementation [here](https://github.com/WavesHQ/bridge/blob/d77497468bca9bbb76a8a726f943a6edbb14682c/apps/server/src/AppService.ts)), I think it will make the UI more complicated?

**Comment by lykalabrada** [comment]
> 
> The thing about point 2: the event can be emitted, but the block that it is mined on might not actually be part of the 'correct' chain. This is a natural process that comes with the consensus mechanisms of the chain.
> 
> Therefore, we should only process 'final' transactions, which happens around 60+ blocks from the tip of the current chain. I think it's possible to have a job that processes historic events (similar to the implementation [here](https://github.com/WavesHQ/bridge/blob/d77497468bca9bbb76a8a726f943a6edbb14682c/apps/server/src/AppService.ts)), I think it will make the UI more complicated?

Hmm, I'm just thinking about "when" to show the success screen to the user and allow them to leave the site. But I guess some message like this should be fine if we are to use [this implementation](https://github.com/WavesHQ/bridge/blob/d77497468bca9bbb76a8a726f943a6edbb14682c/apps/server/src/AppService.ts).
![image](https://user-images.githubusercontent.com/17063281/215746429-a8e8c9e7-29b8-4eaf-becc-7cfcbd39af60.png)

**Comment by weiyuan95** [comment]
> > The thing about point 2: the event can be emitted, but the block that it is mined on might not actually be part of the 'correct' chain. This is a natural process that comes with the consensus mechanisms of the chain.
> > Therefore, we should only process 'final' transactions, which happens around 60+ blocks from the tip of the current chain. I think it's possible to have a job that processes historic events (similar to the implementation [here](https://github.com/WavesHQ/bridge/blob/d77497468bca9bbb76a8a726f943a6edbb14682c/apps/server/src/AppService.ts)), I think it will make the UI more complicated?
> 
> Hmm, I'm just thinking about "when" to show the success screen to the user and allow them to leave the site. But I guess some message like this should be fine if we are to use [this implementation](https://github.com/WavesHQ/bridge/blob/d77497468bca9bbb76a8a726f943a6edbb14682c/apps/server/src/AppService.ts). ![image](https://user-images.githubusercontent.com/17063281/215746429-a8e8c9e7-29b8-4eaf-becc-7cfcbd39af60.png)

Yep! I think this is fine - I think most bridges work this way anyway 🤣

**Comment by thedoublejay** [comment]
Updated description and also created some graphic on flows, let me know if I miss something

![image](https://user-images.githubusercontent.com/25013382/216220157-2033720b-f524-4a94-bdae-513217b3deee.png)
