### ISSUE TITLE
`Server` - Server backend for DFC -> EVM

### ISSUE THREAD

**Issue by weiyuan95** [WavesHQ/bridge#177]
### Blurb
This issue lists out the necessary tasks that we need to work on to successfully bridge tokens from DFC to EVM. It will state out the flow on how funds are bridged from DeFiChain to Ethereum, and then list out the tasks that need to be done to achieve that goal.

Since this part of the bridge is very involved with the UI, it will reference both the server and UI aspects of the flow.

Take note that this does not worry about any potential front end error handling, and is solely worried about bridging the funds. If the front end needs the server to return some kind of information for error handling, that task will need to be evaluated and added.

### Flow
1. User goes to the bridge UI and initiates a bridge transaction from DFC to Ethereum
    - In this case, this _must_  be done from the bridge UI to initiate the necessary logic and flow
2. The UI requests the server to create a unique DFC address for the user to deposit the necessary tokens to
    **- This needs to be a protected endpoint, if not we are susceptible to attacks**  
    - This needs to be somewhat cached/tied up to a specific transaction ID on the client side. To prevent unnecessary generation of addresses. Example, on the UI side, we can generate a random ID. Pass it when generating address, then use it cache the address generator.
4. The server creates the address with its HD wallet, and responds with this new address to the UI. Every address generated will be stored on a DB with necessary index and address created. This will be used on managing the funds on a later step.
5. The user deposits the necessary funds into this address and then clicks `confirm` on the UI
6. The server checks that the user has deposited the necessary amount of funds to carry out the bridge, and that the transaction has reached the necessary number of confirmations
    - We can use the `TransactionConfirmerQueue`, similar to #176 , for this.
    - One possible solution: if we are taking `x` number of blocks as final, we'll need to use the `WhaleAPI` to make a query like `getAccountBalance(acc, currentBlockHeight - x)`. This is because AFAIK, Whale indexes to the tip of the chain, but we only want to act on `final` transactions. Let's use 30 blocks for DeFiChain side
7. The server will use the hot wallet balance as a limit.
9. The client has a "verify" button that will check if the address has the correct balance. This API will check also if the owner of the address provided is the Hot wallet and if the balance has equal amount.
10. Before generating the claim, server should trigger a "/verify" call again. Then, once verified, create a wallet using the index of the server's address (where the user send out the funds). Use it to send back the amounts to the Hot wallet.
11. Once the deposit is verified and within the limit, the user presses `claim tokens`, and fires a request to the server to create an Ethereum transaction. This will be the transaction that will be used when calling the [`claim` function](https://github.com/WavesHQ/bridge/blob/main/packages/smartcontracts/src/contracts/BridgeV1.sol#L231) of the bridge
    - If the transaction crosses the limit, the UI will need to display an appropriate message to the user
9. The server will need to [sign a EIP-712 message ](https://docs.ethers.org/v5/api/signer/#Signer-signTypedData) and use that in the transaction. There is an example of this [here](https://github.com/WavesHQ/bridge/blob/main/packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts). It then returns the built transaction to the UI
12. The UI will then create the necessary transaction on metamask for the user to sign and execute

### Prerequisites
- A SECP_256K1 private key stored on AWS KMS, which will be the private key used to sign claims
- A database to keep track of the indexes used when creating more HD addresses. Can potentially leverage on the redis instance that we'll need to spin up for the `TransactionConfirmerQueue` from #176 

### Tasks
- [ ] Setup a secure AWS KMS key #182
  - This needs to be properly secured. The root user (or some equivalent) will need to provision a role specifically for the server, and no other role other than root should be able to provision this role. This is to prevent anyone else from using this private key to create claims for themselves
- [ ] Server needs to be able to create multiple unique addresses for users to deposit funds to #144 
  - [ ] Either a database to keep track of the index used to create the HD wallet addresses, or potentially leverage on the redis instance from #176
- [ ] Server needs to be able to get 'final' 30 blocks account balances for a given DFC address
- [ ] Server needs to have polling logic to check that the user has deposited the necessary amount of funds to the given account #187
- [ ] Server needs to be able to determine the daily minted amount for a consortium member https://github.com/JellyfishSDK/jellyfish/issues/1961
- [ ] Server needs to build `claim` Ethereum transaction
- [ ] UI metamask integration #145 

![image](https://user-images.githubusercontent.com/25013382/216222436-7f64880f-b077-4f8c-a687-0ce1d0651e56.png)
