### ISSUE TITLE
Order Book - Quantum App

### ISSUE THREAD

**Issue by thedoublejay** [WavesHQ/bridge#866]
## Main Epic 
https://github.com/BirthdayResearch/quantum/issues/862

As much as possible, let's reuse all existing components, validations from Instant flow.

### Main Page

- [ ] Alice must have a way to add orders directly
- [ ] For current users, if they are using "instant" flow and if funds are not enough, we should have some CTA to redirect them to Order book. Something like "Want to try out Order book?"
- [ ] If user is ordering an amount that fits on instant liquidity, display a warning to use Instant instead. Alice should still be able to proceed with Order book transaction.
- [ ] Alice can input any amounts as long as token is supported.
- [ ] Need to highlight the message that "Your funds will be locked for "arbitrary time" (Right now, it's **48 Hours**)". So user knows how much time his funds will be locked.
- [ ] Once Alice fulfills the form, she needs to sign the transaction via Metamask.
- [ ] Create a distinction between Instant tab or Order book tab (Can have a better naming for this)
- [ ] Use the same variable for Instant fees. Currently there are zero fees. But in case we support it in the future.
- [ ] We should have same validations from Instant. Address validation (if valid network address), network switcher etc.
- [ ] Display Available amounts from Metamask
- [ ] Update instant liquidity to show only instant fees

### Status Page
- [ ] There should be a status page to check their current transaction. As much as possible, user should be able to order as many as they want. We need to have an input field that accepts a TX Id and view it. Or, it will be automatically visible from local storage. Similar entrypoint as restore transactions:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/25013382/228442157-48d0e6e9-d1da-48e0-838c-13303135396e.png">

- [ ] If tx id is invalid or not on db, have a warning message on the modal
- [ ] Alice should be able to view his created TX id, status, token amount, details, amount left.

#### Status = Completed
- [ ] Show TX id on DeFiScan. Must wait for 35 confirmations.

#### Status = Error
- [ ] Display error message, users should be able to request for Refund. Ops will fulfill it within the next 48 hours.

#### Status = Refund ready
- [ ] Display button to generate claim and get back their funds

### Refund Flow
- [ ] If there's an error, user should be able to request for refund or claim. I was thinking of making it instant. But for now, let's just have a way to ask for Refund. It will be shown on Admin Dashboard. We can verify it manually then set it to true. Once set to true, user can generate a claim on their side.

### Tasks
- [x] #977 
- [x] #978 
- [x] #979 
- [x] #980 
- [x] #981 
- [x] #982
- [x] #983
