### ISSUE TITLE
Order Book - Quantum Server

### ISSUE THREAD

**Issue by thedoublejay** [WavesHQ/bridge#877]
## Create new DB tables
- [x] #878

## Environment Variables
- [ ] Server Hot Wallet Private Key (Ethereum Queue) - Different from current hot wallet Private key
- [ ] New smart contract address

## Server
- [x] Create an endpoint to create an order transaction, this endpoint should do similar checks like "/verify". Wait for it to be verified 65 confirmations first. `/create` #954 
- [x] Server should have an endpoint to restore orders. Will be used by client to restore on-going orders. `/restore` #957
- [x] Endpoint to request for refund. `/refund` #953 
- [x] Admin panel: Endpoint to return admin details with it's linked order details. `/admin/order` #956
- [x] Order list and single api #955
- [x] Verify DFC tx and update status #976 

Note: endpoint name is an example, feel free to modify as per required
